# Generated by Django 3.0 on 2020-02-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='number_of_ticket',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='mile',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='timetaken',
            field=models.FloatField(null=True),
        ),
    ]
