# Generated by Django 3.0 on 2020-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0002_auto_20200202_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='is_reserved',
            field=models.BooleanField(null=True),
        ),
    ]
