# Generated by Django 3.0 on 2019-12-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='pudate',
        ),
    ]
